### ISSUE TITLE
Add an option to download the database 

### ISSUE THREAD

**Issue by daenuprobst** [BerkaLab/MolMeDB#16]
In order to work on the data (ML, visualization, ...), it would be very advantageous to be able to download the raw data (depending on how it is stored in the backend as a csv, sqlite db, mysql db, ...).

**Comment by BerkaLab** [comment]
This will be a new feature in a new version - since we are moving Project to MolMeDB consortium GitHub 
Issue moved to https://github.com/MolMeDB/MolMeDB/issues/6
